/**
 * Order Template models for quick re-order functionality
 */

export interface OrderTemplateItem {
  productId: number;
  productName: string;
  productSku?: string;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  isAvailable: boolean;
  currentStock?: number;
}

export interface OrderTemplate {
  id: number;
  repId?: number;
  customerId: number;
  customerName: string;
  templateName: string;
  description?: string;
  items: OrderTemplateItem[];
  itemCount: number;
  estimatedTotal: number;
  lastUsedAt?: Date;
  usageCount: number;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export interface CreateOrderTemplateItem {
  productId: number;
  quantity: number;
  unitPrice?: number;
}

export interface CreateOrderTemplateRequest {
  customerId: number;
  templateName: string;
  description?: string;
  items: CreateOrderTemplateItem[];
}

export interface CreateTemplateFromOrderRequest {
  orderId: number;
  templateName: string;
  description?: string;
}

export interface UpdateOrderTemplateRequest {
  templateName: string;
  description?: string;
  items: CreateOrderTemplateItem[];
}

export interface CreateOrderFromTemplateRequest {
  templateId: number;
  visitId?: number;
  notes?: string;
  quantityOverrides?: { [productId: number]: number };
}
