import { Component, OnInit, inject, signal, computed, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';

import { OrderTemplateService } from '../../core/services/order-template.service';
import { NotificationService } from '../../core/services/notification.service';
import {
  OrderTemplate,
  OrderTemplateItem,
  CreateOrderFromTemplateRequest
} from '../../shared/models/order-template.model';

@Component({
  selector: 'app-order-templates',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, TranslateModule],
  template: `
    <div class="templates">
      <div class="templates__header">
        <button class="btn" (click)="back()">
          ← {{ 'common.back' | translate }}
        </button>
        <h1 class="templates__title">
          {{ 'orders.orderTemplates' | translate }}
        </h1>
      </div>

      <!-- Loading State -->
      @if (loading()) {
        <div class="loading-state">
          <div class="spinner"></div>
          <span>{{ 'common.loading' | translate }}</span>
        </div>
      } @else {
        <!-- Suggested Templates -->
        @if (suggestedTemplates().length > 0) {
          <section class="templates__section">
            <h2 class="templates__section-title">
              <span class="icon">💡</span>
              {{ 'orders.suggestedTemplates' | translate }}
            </h2>
            <div class="template-grid">
              @for (template of suggestedTemplates(); track template.id) {
                <div class="template-card template-card--suggested">
                  <div class="template-card__header">
                    <span class="template-card__badge">{{ 'orders.autoGenerated' | translate }}</span>
                  </div>
                  <div class="template-card__body">
                    <h3 class="template-card__name">{{ template.templateName }}</h3>
                    @if (template.description) {
                      <p class="template-card__description">{{ template.description }}</p>
                    }
                    <div class="template-card__stats">
                      <span>{{ template.itemCount }} {{ 'orders.items' | translate }}</span>
                      <span class="template-card__total">{{ template.estimatedTotal | currency:'KM ' }}</span>
                    </div>
                  </div>
                  <div class="template-card__items">
                    @for (item of template.items.slice(0, 3); track item.productId) {
                      <div class="item-preview" [class.item-preview--unavailable]="!item.isAvailable">
                        <span class="item-preview__name">{{ item.productName }}</span>
                        <span class="item-preview__qty">×{{ item.quantity }}</span>
                      </div>
                    }
                    @if (template.items.length > 3) {
                      <div class="item-preview item-preview--more">
                        +{{ template.items.length - 3 }} {{ 'orders.moreItems' | translate }}
                      </div>
                    }
                  </div>
                  <div class="template-card__actions">
                    <button class="btn btn-sm" (click)="viewTemplate(template)">
                      {{ 'common.view' | translate }}
                    </button>
                    <button
                      class="btn btn-sm btn-primary"
                      [disabled]="!hasAvailableItems(template)"
                      (click)="quickReorder(template)"
                    >
                      {{ 'orders.quickReorder' | translate }}
                    </button>
                  </div>
                </div>
              }
            </div>
          </section>
        }

        <!-- Saved Templates -->
        <section class="templates__section">
          <h2 class="templates__section-title">
            <span class="icon">📋</span>
            {{ 'orders.savedTemplates' | translate }}
          </h2>

          @if (templates().length === 0) {
            <div class="empty-state">
              <div class="empty-state__icon">📋</div>
              <h3>{{ 'orders.noTemplates' | translate }}</h3>
              <p>{{ 'orders.noTemplatesDescription' | translate }}</p>
            </div>
          } @else {
            <div class="template-grid">
              @for (template of templates(); track template.id) {
                <div class="template-card">
                  <div class="template-card__body">
                    <h3 class="template-card__name">{{ template.templateName }}</h3>
                    @if (template.description) {
                      <p class="template-card__description">{{ template.description }}</p>
                    }
                    <div class="template-card__stats">
                      <span>{{ template.itemCount }} {{ 'orders.items' | translate }}</span>
                      <span class="template-card__total">{{ template.estimatedTotal | currency:'KM ' }}</span>
                    </div>
                    @if (template.lastUsedAt) {
                      <div class="template-card__meta">
                        {{ 'orders.lastUsed' | translate }}: {{ template.lastUsedAt | date:'short' }}
                      </div>
                    }
                    <div class="template-card__meta">
                      {{ 'orders.usedTimes' | translate:{ count: template.usageCount } }}
                    </div>
                  </div>
                  <div class="template-card__items">
                    @for (item of template.items.slice(0, 3); track item.productId) {
                      <div class="item-preview" [class.item-preview--unavailable]="!item.isAvailable">
                        <span class="item-preview__name">{{ item.productName }}</span>
                        <span class="item-preview__qty">×{{ item.quantity }}</span>
                        @if (item.currentStock !== undefined && item.currentStock < item.quantity) {
                          <span class="item-preview__warning" title="{{ 'orders.lowStock' | translate }}">⚠️</span>
                        }
                      </div>
                    }
                    @if (template.items.length > 3) {
                      <div class="item-preview item-preview--more">
                        +{{ template.items.length - 3 }} {{ 'orders.moreItems' | translate }}
                      </div>
                    }
                  </div>
                  <div class="template-card__actions">
                    <button class="btn btn-sm" (click)="viewTemplate(template)">
                      {{ 'common.view' | translate }}
                    </button>
                    <button class="btn btn-sm btn-outline" (click)="editTemplate(template)">
                      {{ 'common.edit' | translate }}
                    </button>
                    <button
                      class="btn btn-sm btn-primary"
                      [disabled]="!hasAvailableItems(template)"
                      (click)="quickReorder(template)"
                    >
                      {{ 'orders.quickReorder' | translate }}
                    </button>
                    <button class="btn btn-sm btn-danger" (click)="confirmDelete(template)">
                      {{ 'common.delete' | translate }}
                    </button>
                  </div>
                </div>
              }
            </div>
          }
        </section>
      }

      <!-- Template Detail Modal -->
      @if (selectedTemplate()) {
        <div class="modal-overlay" (click)="closeModal()">
          <div class="modal" (click)="$event.stopPropagation()">
            <div class="modal__header">
              <h2>{{ selectedTemplate()!.templateName }}</h2>
              <button class="modal__close" (click)="closeModal()">×</button>
            </div>
            <div class="modal__body">
              @if (selectedTemplate()!.description) {
                <p class="template-description">{{ selectedTemplate()!.description }}</p>
              }
              <table class="items-table">
                <thead>
                  <tr>
                    <th>{{ 'orders.product' | translate }}</th>
                    <th>{{ 'orders.sku' | translate }}</th>
                    <th class="text-right">{{ 'orders.quantity' | translate }}</th>
                    <th class="text-right">{{ 'orders.unitPrice' | translate }}</th>
                    <th class="text-right">{{ 'orders.lineTotal' | translate }}</th>
                    <th class="text-center">{{ 'orders.stock' | translate }}</th>
                  </tr>
                </thead>
                <tbody>
                  @for (item of selectedTemplate()!.items; track item.productId) {
                    <tr [class.row--unavailable]="!item.isAvailable">
                      <td>
                        {{ item.productName }}
                        @if (!item.isAvailable) {
                          <span class="badge badge--danger">{{ 'orders.unavailable' | translate }}</span>
                        }
                      </td>
                      <td>{{ item.productSku || '-' }}</td>
                      <td class="text-right">
                        @if (editingQuantities()) {
                          <input
                            type="number"
                            class="qty-input"
                            min="1"
                            [max]="item.currentStock ?? 9999"
                            [(ngModel)]="quantityOverrides()[item.productId]"
                            (ngModelChange)="updateQuantityOverride(item.productId, $event)"
                          >
                        } @else {
                          {{ item.quantity }}
                        }
                      </td>
                      <td class="text-right">{{ item.unitPrice | currency:'KM ' }}</td>
                      <td class="text-right">{{ item.lineTotal | currency:'KM ' }}</td>
                      <td class="text-center">
                        @if (item.currentStock !== undefined) {
                          <span [class.text-warning]="item.currentStock < item.quantity" [class.text-danger]="item.currentStock === 0">
                            {{ item.currentStock }}
                          </span>
                        } @else {
                          -
                        }
                      </td>
                    </tr>
                  }
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="4" class="text-right"><strong>{{ 'orders.total' | translate }}:</strong></td>
                    <td class="text-right"><strong>{{ selectedTemplate()!.estimatedTotal | currency:'KM ' }}</strong></td>
                    <td></td>
                  </tr>
                </tfoot>
              </table>
            </div>
            <div class="modal__footer">
              <button class="btn" (click)="closeModal()">{{ 'common.close' | translate }}</button>
              <button class="btn btn-outline" (click)="toggleEditQuantities()">
                {{ editingQuantities() ? ('common.done' | translate) : ('orders.adjustQuantities' | translate) }}
              </button>
              <button
                class="btn btn-primary"
                [disabled]="!hasAvailableItems(selectedTemplate()!) || reordering()"
                (click)="quickReorder(selectedTemplate()!)"
              >
                @if (reordering()) {
                  {{ 'common.processing' | translate }}...
                } @else {
                  {{ 'orders.quickReorder' | translate }}
                }
              </button>
            </div>
          </div>
        </div>
      }

      <!-- Delete Confirmation Modal -->
      @if (templateToDelete()) {
        <div class="modal-overlay" (click)="cancelDelete()">
          <div class="modal modal--sm" (click)="$event.stopPropagation()">
            <div class="modal__header">
              <h2>{{ 'orders.deleteTemplate' | translate }}</h2>
              <button class="modal__close" (click)="cancelDelete()">×</button>
            </div>
            <div class="modal__body">
              <p>{{ 'orders.deleteTemplateConfirm' | translate:{ name: templateToDelete()!.templateName } }}</p>
            </div>
            <div class="modal__footer">
              <button class="btn" (click)="cancelDelete()">{{ 'common.cancel' | translate }}</button>
              <button class="btn btn-danger" [disabled]="deleting()" (click)="deleteTemplate()">
                @if (deleting()) {
                  {{ 'common.deleting' | translate }}...
                } @else {
                  {{ 'common.delete' | translate }}
                }
              </button>
            </div>
          </div>
        </div>
      }
    </div>
  `,
  styles: [`
    .templates {
      padding: 1.5rem;
      max-width: 1400px;
      margin: 0 auto;
    }

    .templates__header {
      display: flex;
      align-items: center;
      gap: 1rem;
      margin-bottom: 2rem;
    }

    .templates__title {
      margin: 0;
      font-size: 1.5rem;
    }

    .templates__section {
      margin-bottom: 2rem;
    }

    .templates__section-title {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 1.25rem;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid var(--border-color);
    }

    .template-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
      gap: 1rem;
    }

    .template-card {
      background: var(--card-bg);
      border: 1px solid var(--border-color);
      border-radius: 8px;
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }

    .template-card--suggested {
      border-color: var(--primary-color);
      background: linear-gradient(to bottom, rgba(var(--primary-rgb), 0.05), var(--card-bg));
    }

    .template-card__header {
      padding: 0.5rem 1rem;
      background: var(--primary-color);
      color: white;
    }

    .template-card__badge {
      font-size: 0.75rem;
      font-weight: 500;
    }

    .template-card__body {
      padding: 1rem;
      flex: 1;
    }

    .template-card__name {
      margin: 0 0 0.5rem;
      font-size: 1.1rem;
    }

    .template-card__description {
      margin: 0 0 0.75rem;
      color: var(--text-muted);
      font-size: 0.875rem;
    }

    .template-card__stats {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 0.875rem;
      margin-bottom: 0.5rem;
    }

    .template-card__total {
      font-weight: 600;
      color: var(--primary-color);
    }

    .template-card__meta {
      font-size: 0.75rem;
      color: var(--text-muted);
    }

    .template-card__items {
      padding: 0.75rem 1rem;
      background: var(--bg-muted);
      border-top: 1px solid var(--border-color);
    }

    .item-preview {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 0.875rem;
      padding: 0.25rem 0;
    }

    .item-preview__name {
      flex: 1;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .item-preview__qty {
      color: var(--text-muted);
    }

    .item-preview__warning {
      font-size: 0.75rem;
    }

    .item-preview--unavailable {
      text-decoration: line-through;
      opacity: 0.6;
    }

    .item-preview--more {
      color: var(--text-muted);
      font-style: italic;
    }

    .template-card__actions {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      padding: 1rem;
      border-top: 1px solid var(--border-color);
    }

    .loading-state {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 1rem;
      padding: 3rem;
      color: var(--text-muted);
    }

    .empty-state {
      text-align: center;
      padding: 3rem;
      color: var(--text-muted);
    }

    .empty-state__icon {
      font-size: 3rem;
      margin-bottom: 1rem;
    }

    .modal-overlay {
      position: fixed;
      inset: 0;
      background: rgba(0, 0, 0, 0.5);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
    }

    .modal {
      background: var(--card-bg);
      border-radius: 8px;
      max-width: 800px;
      width: 90%;
      max-height: 80vh;
      display: flex;
      flex-direction: column;
    }

    .modal--sm {
      max-width: 400px;
    }

    .modal__header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 1rem 1.5rem;
      border-bottom: 1px solid var(--border-color);
    }

    .modal__header h2 {
      margin: 0;
      font-size: 1.25rem;
    }

    .modal__close {
      background: none;
      border: none;
      font-size: 1.5rem;
      cursor: pointer;
      padding: 0.25rem;
      line-height: 1;
    }

    .modal__body {
      padding: 1.5rem;
      overflow-y: auto;
      flex: 1;
    }

    .modal__footer {
      display: flex;
      justify-content: flex-end;
      gap: 0.75rem;
      padding: 1rem 1.5rem;
      border-top: 1px solid var(--border-color);
    }

    .items-table {
      width: 100%;
      border-collapse: collapse;
    }

    .items-table th,
    .items-table td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid var(--border-color);
    }

    .items-table th {
      font-weight: 600;
      background: var(--bg-muted);
    }

    .items-table .text-right {
      text-align: right;
    }

    .items-table .text-center {
      text-align: center;
    }

    .row--unavailable {
      opacity: 0.6;
      background: var(--bg-muted);
    }

    .qty-input {
      width: 60px;
      padding: 0.25rem 0.5rem;
      border: 1px solid var(--border-color);
      border-radius: 4px;
      text-align: center;
    }

    .badge {
      display: inline-block;
      font-size: 0.65rem;
      padding: 0.125rem 0.375rem;
      border-radius: 3px;
      margin-left: 0.5rem;
    }

    .badge--danger {
      background: var(--danger-color);
      color: white;
    }

    .text-warning {
      color: var(--warning-color);
    }

    .text-danger {
      color: var(--danger-color);
    }

    .spinner {
      width: 24px;
      height: 24px;
      border: 2px solid var(--border-color);
      border-top-color: var(--primary-color);
      border-radius: 50%;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  `]
})
export class OrderTemplatesComponent implements OnInit {
  private readonly templateService = inject(OrderTemplateService);
  private readonly notificationService = inject(NotificationService);
  private readonly router = inject(Router);

  // Input for customer context
  customerId = input<number>();

  // State
  loading = signal(true);
  templates = signal<OrderTemplate[]>([]);
  suggestedTemplates = signal<OrderTemplate[]>([]);
  selectedTemplate = signal<OrderTemplate | null>(null);
  templateToDelete = signal<OrderTemplate | null>(null);
  editingQuantities = signal(false);
  quantityOverrides = signal<{ [productId: number]: number }>({});
  reordering = signal(false);
  deleting = signal(false);

  ngOnInit(): void {
    this.loadTemplates();
  }

  private loadTemplates(): void {
    this.loading.set(true);

    const custId = this.customerId();
    if (custId) {
      // Load templates for specific customer
      this.templateService.getTemplatesForCustomer(custId).subscribe({
        next: (templates) => {
          this.templates.set(templates.filter(t => !t.isAutoGenerated));
          this.loading.set(false);
        },
        error: (err) => {
          console.error('Failed to load templates', err);
          this.notificationService.error('Failed to load order templates');
          this.loading.set(false);
        }
      });

      // Load suggested templates
      this.templateService.getSuggestedTemplates(custId).subscribe({
        next: (templates) => this.suggestedTemplates.set(templates),
        error: (err) => console.error('Failed to load suggested templates', err)
      });
    } else {
      // Load all rep templates
      this.templateService.getMyTemplates().subscribe({
        next: (templates) => {
          this.templates.set(templates);
          this.loading.set(false);
        },
        error: (err) => {
          console.error('Failed to load templates', err);
          this.notificationService.error('Failed to load order templates');
          this.loading.set(false);
        }
      });
    }
  }

  back(): void {
    window.history.back();
  }

  viewTemplate(template: OrderTemplate): void {
    this.selectedTemplate.set(template);
    this.editingQuantities.set(false);
    // Initialize quantity overrides with current quantities
    const overrides: { [productId: number]: number } = {};
    template.items.forEach(item => {
      overrides[item.productId] = item.quantity;
    });
    this.quantityOverrides.set(overrides);
  }

  closeModal(): void {
    this.selectedTemplate.set(null);
    this.editingQuantities.set(false);
  }

  editTemplate(template: OrderTemplate): void {
    // Navigate to edit page or show edit modal
    this.router.navigate(['/orders/templates', template.id, 'edit']);
  }

  toggleEditQuantities(): void {
    this.editingQuantities.set(!this.editingQuantities());
  }

  updateQuantityOverride(productId: number, quantity: number): void {
    const overrides = { ...this.quantityOverrides() };
    overrides[productId] = quantity;
    this.quantityOverrides.set(overrides);
  }

  hasAvailableItems(template: OrderTemplate): boolean {
    return template.items.some(item => item.isAvailable);
  }

  quickReorder(template: OrderTemplate): void {
    this.reordering.set(true);

    const request: CreateOrderFromTemplateRequest = {
      templateId: template.id,
      quantityOverrides: this.editingQuantities() ? this.quantityOverrides() : undefined
    };

    this.templateService.createOrderFromTemplate(request).subscribe({
      next: (order) => {
        this.reordering.set(false);
        this.closeModal();
        this.notificationService.success(`Order ${order.orderNumber} created successfully!`);
        this.router.navigate(['/orders', order.orderId]);
      },
      error: (err) => {
        this.reordering.set(false);
        console.error('Failed to create order', err);
        this.notificationService.error(err.error?.message || 'Failed to create order from template');
      }
    });
  }

  confirmDelete(template: OrderTemplate): void {
    this.templateToDelete.set(template);
  }

  cancelDelete(): void {
    this.templateToDelete.set(null);
  }

  deleteTemplate(): void {
    const template = this.templateToDelete();
    if (!template) return;

    this.deleting.set(true);

    this.templateService.deleteTemplate(template.id).subscribe({
      next: () => {
        this.deleting.set(false);
        this.templateToDelete.set(null);
        this.templates.set(this.templates().filter(t => t.id !== template.id));
        this.notificationService.success('Template deleted successfully');
      },
      error: (err) => {
        this.deleting.set(false);
        console.error('Failed to delete template', err);
        this.notificationService.error('Failed to delete template');
      }
    });
  }
}
