namespace Domain.Entities;

/// <summary>
/// Represents a saved order template for quick re-ordering.
/// Can be created by sales reps for their customers, or by customers themselves.
/// </summary>
public class OrderTemplate : BaseEntity
{
    /// <summary>
    /// Sales rep who created the template (null if created by customer)
    /// </summary>
    public int? RepId { get; set; }
    
    /// <summary>
    /// Customer this template belongs to
    /// </summary>
    public int CustomerId { get; set; }
    
    /// <summary>
    /// Display name for the template
    /// </summary>
    public string TemplateName { get; set; } = string.Empty;
    
    /// <summary>
    /// Optional description
    /// </summary>
    public string? Description { get; set; }
    
    /// <summary>
    /// JSON array of template items: [{productId, quantity, unitPrice}]
    /// </summary>
    public string ItemsJson { get; set; } = "[]";
    
    /// <summary>
    /// When the template was last used to create an order
    /// </summary>
    public DateTime? LastUsedAt { get; set; }
    
    /// <summary>
    /// Number of times this template has been used
    /// </summary>
    public int UsageCount { get; set; } = 0;
    
    /// <summary>
    /// Whether this is a system-suggested template based on order patterns
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;
    
    /// <summary>
    /// Whether template is active (not deleted)
    /// </summary>
    public bool IsActive { get; set; } = true;
    
    // Navigation properties
    public virtual SalesRepresentative? Rep { get; set; }
    public virtual Customer Customer { get; set; } = null!;
}
