namespace Application.DTOs.Orders;

/// <summary>
/// DTO for order template list/summary
/// </summary>
public class OrderTemplateDto
{
    public int Id { get; set; }
    public int? RepId { get; set; }
    public int CustomerId { get; set; }
    public string CustomerName { get; set; } = string.Empty;
    public string TemplateName { get; set; } = string.Empty;
    public string? Description { get; set; }
    public List<OrderTemplateItemDto> Items { get; set; } = new();
    public int ItemCount { get; set; }
    public decimal EstimatedTotal { get; set; }
    public DateTime? LastUsedAt { get; set; }
    public int UsageCount { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// Individual item in a template
/// </summary>
public class OrderTemplateItemDto
{
    public int ProductId { get; set; }
    public string ProductName { get; set; } = string.Empty;
    public string? ProductSku { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal LineTotal => Quantity * UnitPrice;
    public bool IsAvailable { get; set; } = true;
    public int CurrentStock { get; set; }
}

/// <summary>
/// Request to create a new order template
/// </summary>
public class CreateOrderTemplateDto
{
    public int CustomerId { get; set; }
    public string TemplateName { get; set; } = string.Empty;
    public string? Description { get; set; }
    public List<CreateOrderTemplateItemDto> Items { get; set; } = new();
}

/// <summary>
/// Item for creating template
/// </summary>
public class CreateOrderTemplateItemDto
{
    public int ProductId { get; set; }
    public int Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
}

/// <summary>
/// Request to create template from existing order
/// </summary>
public class CreateTemplateFromOrderDto
{
    public int OrderId { get; set; }
    public string TemplateName { get; set; } = string.Empty;
    public string? Description { get; set; }
}

/// <summary>
/// Request to update an existing template
/// </summary>
public class UpdateOrderTemplateDto
{
    public string TemplateName { get; set; } = string.Empty;
    public string? Description { get; set; }
    public List<CreateOrderTemplateItemDto> Items { get; set; } = new();
}

/// <summary>
/// Request to create order from template
/// </summary>
public class CreateOrderFromTemplateDto
{
    public int TemplateId { get; set; }
    public int? VisitId { get; set; }
    public string? Notes { get; set; }
    /// <summary>
    /// Optional: override quantities from template
    /// </summary>
    public Dictionary<int, int>? QuantityOverrides { get; set; }
}
